package seed

import (
	"log"
	"time"

	"github.com/winterheatherica/tokoaku-backend/internal/models"
	"gorm.io/gorm"
)

func SeedBankLists(db *gorm.DB) {
	bankLists := []models.BankList{
		{Name: "BANK BRI", FullName: "BANK BANK RAKYAT INDOENSIA", Code: "002", CreatedAt: time.Now()},
		{Name: "BANK EKSPOR INDONESIA", FullName: "BANK EKSPOR INDONESIA", Code: "003", CreatedAt: time.Now()},
		{Name: "BANK MANDIRI", FullName: "BANK MANDIRI", Code: "008", CreatedAt: time.Now()},
		{Name: "BANK BNI", FullName: "BANK BNI", Code: "009", CreatedAt: time.Now()},
		{Name: "BANK DANAMON", FullName: "BANK DANAMON", Code: "011", CreatedAt: time.Now()},
		{Name: "PERMATA BANK", FullName: "PERMATA BANK", Code: "013", CreatedAt: time.Now()},
		{Name: "BANK BCA", FullName: "BANK BCA", Code: "014", CreatedAt: time.Now()},
		{Name: "BANK BII", FullName: "BANK BII", Code: "016", CreatedAt: time.Now()},
		{Name: "BANK PANIN", FullName: "BANK PANIN", Code: "019", CreatedAt: time.Now()},
		{Name: "BANK ARTA NIAGA KENCANA", FullName: "BANK ARTA NIAGA KENCANA", Code: "020", CreatedAt: time.Now()},
		{Name: "BANK NIAGA", FullName: "BANK NIAGA", Code: "022", CreatedAt: time.Now()},
		{Name: "BANK BUANA IND", FullName: "BANK BUANA IND", Code: "023", CreatedAt: time.Now()},
		{Name: "BANK LIPPO", FullName: "BANK LIPPO", Code: "026", CreatedAt: time.Now()},
		{Name: "BANK NISP", FullName: "BANK NISP", Code: "028", CreatedAt: time.Now()},
		{Name: "AMERICAN EXPRESS BANK LTD", FullName: "AMERICAN EXPRESS BANK LTD", Code: "030", CreatedAt: time.Now()},
		{Name: "CITIBANK N.A.", FullName: "CITIBANK N.A.", Code: "031", CreatedAt: time.Now()},
		{Name: "JP. MORGAN CHASE BANK, N.A.", FullName: "JP. MORGAN CHASE BANK, N.A.", Code: "032", CreatedAt: time.Now()},
		{Name: "BANK OF AMERICA, N.A", FullName: "BANK OF AMERICA, N.A", Code: "033", CreatedAt: time.Now()},
		{Name: "ING INDONESIA BANK", FullName: "ING INDONESIA BANK", Code: "034", CreatedAt: time.Now()},
		{Name: "BANK MULTICOR TBK.", FullName: "BANK MULTICOR TBK.", Code: "036", CreatedAt: time.Now()},
		{Name: "BANK ARTHA GRAHA", FullName: "BANK ARTHA GRAHA", Code: "037", CreatedAt: time.Now()},
		{Name: "BANK CREDIT AGRICOLE INDOSUEZ", FullName: "BANK CREDIT AGRICOLE INDOSUEZ", Code: "039", CreatedAt: time.Now()},
		{Name: "THE BANGKOK BANK COMP. LTD", FullName: "THE BANGKOK BANK COMP. LTD", Code: "040", CreatedAt: time.Now()},
		{Name: "THE HONGKONG & SHANGHAI B.C.", FullName: "THE HONGKONG & SHANGHAI B.C.", Code: "041", CreatedAt: time.Now()},
		{Name: "THE BANK OF TOKYO MITSUBISHI UFJ LTD", FullName: "THE BANK OF TOKYO MITSUBISHI UFJ LTD", Code: "042", CreatedAt: time.Now()},
		{Name: "BANK SUMITOMO MITSUI INDONESIA", FullName: "BANK SUMITOMO MITSUI INDONESIA", Code: "045", CreatedAt: time.Now()},
		{Name: "BANK DBS INDONESIA", FullName: "BANK DBS INDONESIA", Code: "046", CreatedAt: time.Now()},
		{Name: "BANK RESONA PERDANIA", FullName: "BANK RESONA PERDANIA", Code: "047", CreatedAt: time.Now()},
		{Name: "BANK MIZUHO INDONESIA", FullName: "BANK MIZUHO INDONESIA", Code: "048", CreatedAt: time.Now()},
		{Name: "STANDARD CHARTERED BANK", FullName: "STANDARD CHARTERED BANK", Code: "050", CreatedAt: time.Now()},
		{Name: "BANK ABN AMRO", FullName: "BANK ABN AMRO", Code: "052", CreatedAt: time.Now()},
		{Name: "BANK KEPPEL TATLEE BUANA", FullName: "BANK KEPPEL TATLEE BUANA", Code: "053", CreatedAt: time.Now()},
		{Name: "BANK CAPITAL INDONESIA, TBK.", FullName: "BANK CAPITAL INDONESIA, TBK.", Code: "054", CreatedAt: time.Now()},
		{Name: "BANK BNP PARIBAS INDONESIA", FullName: "BANK BNP PARIBAS INDONESIA", Code: "057", CreatedAt: time.Now()},
		{Name: "BANK UOB INDONESIA", FullName: "BANK UOB INDONESIA", Code: "058", CreatedAt: time.Now()},
		{Name: "KOREA EXCHANGE BANK DANAMON", FullName: "KOREA EXCHANGE BANK DANAMON", Code: "059", CreatedAt: time.Now()},
		{Name: "RABOBANK INTERNASIONAL INDONESIA", FullName: "RABOBANK INTERNASIONAL INDONESIA", Code: "060", CreatedAt: time.Now()},
		{Name: "ANZ PANIN BANK", FullName: "ANZ PANIN BANK", Code: "061", CreatedAt: time.Now()},
		{Name: "DEUTSCHE BANK AG.", FullName: "DEUTSCHE BANK AG.", Code: "067", CreatedAt: time.Now()},
		{Name: "BANK WOORI INDONESIA", FullName: "BANK WOORI INDONESIA", Code: "068", CreatedAt: time.Now()},
		{Name: "BANK OF CHINA LIMITED", FullName: "BANK OF CHINA LIMITED", Code: "069", CreatedAt: time.Now()},
		{Name: "BANK BUMI ARTA", FullName: "BANK BUMI ARTA", Code: "076", CreatedAt: time.Now()},
		{Name: "BANK EKONOMI", FullName: "BANK EKONOMI", Code: "087", CreatedAt: time.Now()},
		{Name: "BANK ANTARDAERAH", FullName: "BANK ANTARDAERAH", Code: "088", CreatedAt: time.Now()},
		{Name: "BANK HAGA", FullName: "BANK HAGA", Code: "089", CreatedAt: time.Now()},
		{Name: "BANK IFI", FullName: "BANK IFI", Code: "093", CreatedAt: time.Now()},
		{Name: "BANK CENTURY, TBK.", FullName: "BANK CENTURY, TBK.", Code: "095", CreatedAt: time.Now()},
		{Name: "BANK MAYAPADA", FullName: "BANK MAYAPADA", Code: "097", CreatedAt: time.Now()},
		{Name: "BANK JABAR", FullName: "BANK JABAR", Code: "110", CreatedAt: time.Now()},
		{Name: "BANK DKI", FullName: "BANK DKI", Code: "111", CreatedAt: time.Now()},
		{Name: "BPD DIY", FullName: "BPD DIY", Code: "112", CreatedAt: time.Now()},
		{Name: "BANK JATENG", FullName: "BANK JATENG", Code: "113", CreatedAt: time.Now()},
		{Name: "BANK JATIM", FullName: "BANK JATIM", Code: "114", CreatedAt: time.Now()},
		{Name: "BPD JAMBI", FullName: "BPD JAMBI", Code: "115", CreatedAt: time.Now()},
		{Name: "BPD ACEH", FullName: "BPD ACEH", Code: "116", CreatedAt: time.Now()},
		{Name: "BANK SUMUT", FullName: "BANK SUMUT", Code: "117", CreatedAt: time.Now()},
		{Name: "BANK NAGARI", FullName: "BANK NAGARI", Code: "118", CreatedAt: time.Now()},
		{Name: "BANK RIAU", FullName: "BANK RIAU", Code: "119", CreatedAt: time.Now()},
		{Name: "BANK SUMSEL", FullName: "BANK SUMSEL", Code: "120", CreatedAt: time.Now()},
		{Name: "BANK LAMPUNG", FullName: "BANK LAMPUNG", Code: "121", CreatedAt: time.Now()},
		{Name: "BPD KALSEL", FullName: "BPD KALSEL", Code: "122", CreatedAt: time.Now()},
		{Name: "BPD KALIMANTAN BARAT", FullName: "BPD KALIMANTAN BARAT", Code: "123", CreatedAt: time.Now()},
		{Name: "BPD KALTIM", FullName: "BPD KALTIM", Code: "124", CreatedAt: time.Now()},
		{Name: "BPD KALTENG", FullName: "BPD KALTENG", Code: "125", CreatedAt: time.Now()},
		{Name: "BPD SULSEL", FullName: "BPD SULSEL", Code: "126", CreatedAt: time.Now()},
		{Name: "BANK SULUT", FullName: "BANK SULUT", Code: "127", CreatedAt: time.Now()},
		{Name: "BPD NTB", FullName: "BPD NTB", Code: "128", CreatedAt: time.Now()},
		{Name: "BPD BALI", FullName: "BPD BALI", Code: "129", CreatedAt: time.Now()},
		{Name: "BANK NTT", FullName: "BANK NTT", Code: "130", CreatedAt: time.Now()},
		{Name: "BANK MALUKU", FullName: "BANK MALUKU", Code: "131", CreatedAt: time.Now()},
		{Name: "BPD PAPUA", FullName: "BPD PAPUA", Code: "132", CreatedAt: time.Now()},
		{Name: "BANK BENGKULU", FullName: "BANK BENGKULU", Code: "133", CreatedAt: time.Now()},
		{Name: "BPD SULAWESI TENGAH", FullName: "BPD SULAWESI TENGAH", Code: "134", CreatedAt: time.Now()},
		{Name: "BANK SULTRA", FullName: "BANK SULTRA", Code: "135", CreatedAt: time.Now()},
		{Name: "BANK NUSANTARA PARAHYANGAN", FullName: "BANK NUSANTARA PARAHYANGAN", Code: "145", CreatedAt: time.Now()},
		{Name: "BANK SWADESI", FullName: "BANK SWADESI", Code: "146", CreatedAt: time.Now()},
		{Name: "BANK MUAMALAT", FullName: "BANK MUAMALAT", Code: "147", CreatedAt: time.Now()},
		{Name: "BANK MESTIKA", FullName: "BANK MESTIKA", Code: "151", CreatedAt: time.Now()},
		{Name: "BANK METRO EXPRESS", FullName: "BANK METRO EXPRESS", Code: "152", CreatedAt: time.Now()},
		{Name: "BANK SHINTA INDONESIA", FullName: "BANK SHINTA INDONESIA", Code: "153", CreatedAt: time.Now()},
		{Name: "BANK MASPION", FullName: "BANK MASPION", Code: "157", CreatedAt: time.Now()},
		{Name: "BANK HAGAKITA", FullName: "BANK HAGAKITA", Code: "159", CreatedAt: time.Now()},
		{Name: "BANK GANESHA", FullName: "BANK GANESHA", Code: "161", CreatedAt: time.Now()},
		{Name: "BANK WINDU KENTJANA", FullName: "BANK WINDU KENTJANA", Code: "162", CreatedAt: time.Now()},
		{Name: "HALIM INDONESIA BANK", FullName: "HALIM INDONESIA BANK", Code: "164", CreatedAt: time.Now()},
		{Name: "BANK HARMONI INTERNATIONAL", FullName: "BANK HARMONI INTERNATIONAL", Code: "166", CreatedAt: time.Now()},
		{Name: "BANK KESAWAN", FullName: "BANK KESAWAN", Code: "167", CreatedAt: time.Now()},
		{Name: "BANK TABUNGAN NEGARA (PERSERO)", FullName: "BANK TABUNGAN NEGARA (PERSERO)", Code: "200", CreatedAt: time.Now()},
		{Name: "BANK HIMPUNAN SAUDARA 1906, TBK .", FullName: "BANK HIMPUNAN SAUDARA 1906, TBK .", Code: "212", CreatedAt: time.Now()},
		{Name: "BANK TABUNGAN PENSIUNAN NASIONAL", FullName: "BANK TABUNGAN PENSIUNAN NASIONAL", Code: "213", CreatedAt: time.Now()},
		{Name: "BANK SWAGUNA", FullName: "BANK SWAGUNA", Code: "405", CreatedAt: time.Now()},
		{Name: "BANK JASA ARTA", FullName: "BANK JASA ARTA", Code: "422", CreatedAt: time.Now()},
		{Name: "BANK MEGA", FullName: "BANK MEGA", Code: "426", CreatedAt: time.Now()},
		{Name: "BANK JASA JAKARTA", FullName: "BANK JASA JAKARTA", Code: "427", CreatedAt: time.Now()},
		{Name: "BANK BUKOPIN", FullName: "BANK BUKOPIN", Code: "441", CreatedAt: time.Now()},
		{Name: "BANK SYARIAH MANDIRI", FullName: "BANK SYARIAH MANDIRI", Code: "451", CreatedAt: time.Now()},
		{Name: "BANK BISNIS INTERNASIONAL", FullName: "BANK BISNIS INTERNASIONAL", Code: "459", CreatedAt: time.Now()},
		{Name: "BANK SRI PARTHA", FullName: "BANK SRI PARTHA", Code: "466", CreatedAt: time.Now()},
		{Name: "BANK JASA JAKARTA", FullName: "BANK JASA JAKARTA", Code: "472", CreatedAt: time.Now()},
		{Name: "BANK BINTANG MANUNGGAL", FullName: "BANK BINTANG MANUNGGAL", Code: "484", CreatedAt: time.Now()},
		{Name: "BANK BUMIPUTERA", FullName: "BANK BUMIPUTERA", Code: "485", CreatedAt: time.Now()},
		{Name: "BANK YUDHA BHAKTI", FullName: "BANK YUDHA BHAKTI", Code: "490", CreatedAt: time.Now()},
		{Name: "BANK MITRANIAGA", FullName: "BANK MITRANIAGA", Code: "491", CreatedAt: time.Now()},
		{Name: "BANK AGRO NIAGA", FullName: "BANK AGRO NIAGA", Code: "494", CreatedAt: time.Now()},
		{Name: "BANK INDOMONEX", FullName: "BANK INDOMONEX", Code: "498", CreatedAt: time.Now()},
		{Name: "BANK ROYAL INDONESIA", FullName: "BANK ROYAL INDONESIA", Code: "501", CreatedAt: time.Now()},
		{Name: "BANK ALFINDO", FullName: "BANK ALFINDO", Code: "503", CreatedAt: time.Now()},
		{Name: "BANK SYARIAH MEGA", FullName: "BANK SYARIAH MEGA", Code: "506", CreatedAt: time.Now()},
		{Name: "BANK INA PERDANA", FullName: "BANK INA PERDANA", Code: "513", CreatedAt: time.Now()},
		{Name: "BANK HARFA", FullName: "BANK HARFA", Code: "517", CreatedAt: time.Now()},
		{Name: "PRIMA MASTER BANK", FullName: "PRIMA MASTER BANK", Code: "520", CreatedAt: time.Now()},
		{Name: "BANK PERSYARIKATAN INDONESIA", FullName: "BANK PERSYARIKATAN INDONESIA", Code: "521", CreatedAt: time.Now()},
		{Name: "BANK DIPO INTERNATIONAL", FullName: "BANK DIPO INTERNATIONAL", Code: "523", CreatedAt: time.Now()},
		{Name: "BANK AKITA", FullName: "BANK AKITA", Code: "525", CreatedAt: time.Now()},
		{Name: "LIMAN INTERNATIONAL BANK", FullName: "LIMAN INTERNATIONAL BANK", Code: "526", CreatedAt: time.Now()},
		{Name: "ANGLOMAS INTERNASIONAL BANK", FullName: "ANGLOMAS INTERNASIONAL BANK", Code: "531", CreatedAt: time.Now()},
		{Name: "BANK KESEJAHTERAAN EKONOMI", FullName: "BANK KESEJAHTERAAN EKONOMI", Code: "535", CreatedAt: time.Now()},
		{Name: "BANK UIB", FullName: "BANK UIB", Code: "536", CreatedAt: time.Now()},
		{Name: "BANK ARTOS IND", FullName: "BANK ARTOS IND", Code: "542", CreatedAt: time.Now()},
		{Name: "BANK PURBA DANARTA", FullName: "BANK PURBA DANARTA", Code: "547", CreatedAt: time.Now()},
		{Name: "BANK MULTI ARTA SENTOSA", FullName: "BANK MULTI ARTA SENTOSA", Code: "548", CreatedAt: time.Now()},
		{Name: "BANK MAYORA", FullName: "BANK MAYORA", Code: "553", CreatedAt: time.Now()},
		{Name: "BANK INDEX SELINDO", FullName: "BANK INDEX SELINDO", Code: "555", CreatedAt: time.Now()},
		{Name: "BANK VICTORIA INTERNATIONAL", FullName: "BANK VICTORIA INTERNATIONAL", Code: "566", CreatedAt: time.Now()},
		{Name: "BANK EKSEKUTIF", FullName: "BANK EKSEKUTIF", Code: "558", CreatedAt: time.Now()},
		{Name: "CENTRATAMA NASIONAL BANK", FullName: "CENTRATAMA NASIONAL BANK", Code: "559", CreatedAt: time.Now()},
		{Name: "BANK FAMA INTERNASIONAL", FullName: "BANK FAMA INTERNASIONAL", Code: "562", CreatedAt: time.Now()},
		{Name: "BANK SINAR HARAPAN BALI", FullName: "BANK SINAR HARAPAN BALI", Code: "564", CreatedAt: time.Now()},
		{Name: "BANK HARDA", FullName: "BANK HARDA", Code: "567", CreatedAt: time.Now()},
		{Name: "BANK FINCONESIA", FullName: "BANK FINCONESIA", Code: "945", CreatedAt: time.Now()},
		{Name: "BANK MERINCORP", FullName: "BANK MERINCORP", Code: "946", CreatedAt: time.Now()},
		{Name: "BANK MAYBANK INDOCORP", FullName: "BANK MAYBANK INDOCORP", Code: "947", CreatedAt: time.Now()},
		{Name: "BANK OCBC – INDONESIA", FullName: "BANK OCBC – INDONESIA", Code: "948", CreatedAt: time.Now()},
		{Name: "BANK CHINA TRUST INDONESIA", FullName: "BANK CHINA TRUST INDONESIA", Code: "949", CreatedAt: time.Now()},
		{Name: "BANK COMMONWEALTH", FullName: "BANK COMMONWEALTH", Code: "950", CreatedAt: time.Now()},
		{Name: "BANK BJB SYARIAH", FullName: "BANK BJB SYARIAH", Code: "425", CreatedAt: time.Now()},
		{Name: "BPR KS (KARYAJATNIKA SEDAYA)", FullName: "BPR KS (KARYAJATNIKA SEDAYA)", Code: "688", CreatedAt: time.Now()},
		{Name: "LINKAJA", FullName: "LINKAJA", Code: "911", CreatedAt: time.Now()},
	}

	for _, b := range bankLists {
		bank := b
		if err := db.FirstOrCreate(&bank, models.BankList{Code: bank.Code}).Error; err != nil {
			log.Printf("Gagal seeding bank %s: %v\n", bank.Name, err)
		}
	}

	log.Println("[SEEDER] ⚙️  bank lists seeded")
}
