package seed

import (
	"log"
	"time"

	"github.com/winterheatherica/tokoaku-backend/internal/models"
	"gorm.io/gorm"
)

func SeedCategories(db *gorm.DB) {
	categories := []models.Category{
		{Name: "Red", Slug: "red", CreatedAt: time.Now()},
		{Name: "Blue", Slug: "blue", CreatedAt: time.Now()},
		{Name: "Green", Slug: "green", CreatedAt: time.Now()},
		{Name: "Minimalist", Slug: "minimalist", CreatedAt: time.Now()},
		{Name: "Vintage", Slug: "vintage", CreatedAt: time.Now()},
		{Name: "Eco-friendly", Slug: "eco-friendly", CreatedAt: time.Now()},
		{Name: "Waterproof", Slug: "waterproof", CreatedAt: time.Now()},
		{Name: "Soft", Slug: "soft", CreatedAt: time.Now()},
		{Name: "Handmade", Slug: "handmade", CreatedAt: time.Now()},
		{Name: "Premium", Slug: "premium", CreatedAt: time.Now()},
		{Name: "Durable", Slug: "durable", CreatedAt: time.Now()},
		{Name: "Limited Edition", Slug: "limited-edition", CreatedAt: time.Now()},
		{Name: "Organic", Slug: "organic", CreatedAt: time.Now()},
		{Name: "Recycled", Slug: "recycled", CreatedAt: time.Now()},
		{Name: "Elegant", Slug: "elegant", CreatedAt: time.Now()},
		{Name: "Casual", Slug: "casual", CreatedAt: time.Now()},
		{Name: "Sporty", Slug: "sporty", CreatedAt: time.Now()},
		{Name: "Unisex", Slug: "unisex", CreatedAt: time.Now()},
		{Name: "Outdoor", Slug: "outdoor", CreatedAt: time.Now()},
		{Name: "Indoor", Slug: "indoor", CreatedAt: time.Now()},
		{Name: "Wireless", Slug: "wireless", CreatedAt: time.Now()},
		{Name: "Portable", Slug: "portable", CreatedAt: time.Now()},
		{Name: "Smart", Slug: "smart", CreatedAt: time.Now()},
		{Name: "Luxury", Slug: "luxury", CreatedAt: time.Now()},
		{Name: "Rustic", Slug: "rustic", CreatedAt: time.Now()},
		{Name: "Colorful", Slug: "colorful", CreatedAt: time.Now()},
		{Name: "Modern", Slug: "modern", CreatedAt: time.Now()},
		{Name: "Classic", Slug: "classic", CreatedAt: time.Now()},
		{Name: "Compact", Slug: "compact", CreatedAt: time.Now()},
		{Name: "Foldable", Slug: "foldable", CreatedAt: time.Now()},
		{Name: "Multi-purpose", Slug: "multi-purpose", CreatedAt: time.Now()},
		{Name: "Adjustable", Slug: "adjustable", CreatedAt: time.Now()},
		{Name: "Rechargeable", Slug: "rechargeable", CreatedAt: time.Now()},
		{Name: "Silent", Slug: "silent", CreatedAt: time.Now()},
		{Name: "Fast Charging", Slug: "fast-charging", CreatedAt: time.Now()},
		{Name: "Sustainable", Slug: "sustainable", CreatedAt: time.Now()},
		{Name: "Eco Packaging", Slug: "eco-packaging", CreatedAt: time.Now()},
		{Name: "Limited Stock", Slug: "limited-stock", CreatedAt: time.Now()},
		{Name: "New Arrival", Slug: "new-arrival", CreatedAt: time.Now()},
		{Name: "Best Seller", Slug: "best-seller", CreatedAt: time.Now()},
		{Name: "Kids Friendly", Slug: "kids-friendly", CreatedAt: time.Now()},
		{Name: "Pet Friendly", Slug: "pet-friendly", CreatedAt: time.Now()},
		{Name: "Travel Essential", Slug: "travel-essential", CreatedAt: time.Now()},
		{Name: "Cooling", Slug: "cooling", CreatedAt: time.Now()},
		{Name: "Heated", Slug: "heated", CreatedAt: time.Now()},
		{Name: "Breathable", Slug: "breathable", CreatedAt: time.Now()},
		{Name: "Stylish", Slug: "stylish", CreatedAt: time.Now()},
		{Name: "Budget", Slug: "budget", CreatedAt: time.Now()},
		{Name: "High Performance", Slug: "high-performance", CreatedAt: time.Now()},
		{Name: "Compact Size", Slug: "compact-size", CreatedAt: time.Now()},
		{Name: "Earth Tone", Slug: "earth-tone", CreatedAt: time.Now()},
		{Name: "Space-Saving", Slug: "space-saving", CreatedAt: time.Now()},
		{Name: "Bohemian", Slug: "bohemian", CreatedAt: time.Now()},
		{Name: "Feminine", Slug: "feminine", CreatedAt: time.Now()},
		{Name: "Masculine", Slug: "masculine", CreatedAt: time.Now()},
		{Name: "Tech-Ready", Slug: "tech-ready", CreatedAt: time.Now()},
		{Name: "Luxury Look", Slug: "luxury-look", CreatedAt: time.Now()},
		{Name: "Matte Finish", Slug: "matte-finish", CreatedAt: time.Now()},
		{Name: "Glossy", Slug: "glossy", CreatedAt: time.Now()},
		{Name: "Seasonal", Slug: "seasonal", CreatedAt: time.Now()},
		{Name: "Elegant Black", Slug: "elegant-black", CreatedAt: time.Now()},
		{Name: "Pastel Colors", Slug: "pastel-colors", CreatedAt: time.Now()},
		{Name: "Neon Bright", Slug: "neon-bright", CreatedAt: time.Now()},
		{Name: "Bold Print", Slug: "bold-print", CreatedAt: time.Now()},
		{Name: "Nature Inspired", Slug: "nature-inspired", CreatedAt: time.Now()},
		{Name: "Compact Living", Slug: "compact-living", CreatedAt: time.Now()},
		{Name: "Family Friendly", Slug: "family-friendly", CreatedAt: time.Now()},
		{Name: "Kid Safe", Slug: "kid-safe", CreatedAt: time.Now()},
		{Name: "Easy Install", Slug: "easy-install", CreatedAt: time.Now()},
		{Name: "Zero Waste", Slug: "zero-waste", CreatedAt: time.Now()},
		{Name: "Cold Weather", Slug: "cold-weather", CreatedAt: time.Now()},
		{Name: "Hot Weather", Slug: "hot-weather", CreatedAt: time.Now()},
		{Name: "Antibacterial", Slug: "antibacterial", CreatedAt: time.Now()},
		{Name: "Hypoallergenic", Slug: "hypoallergenic", CreatedAt: time.Now()},
		{Name: "Multicolor", Slug: "multicolor", CreatedAt: time.Now()},
		{Name: "Quick Dry", Slug: "quick-dry", CreatedAt: time.Now()},
		{Name: "Tear Resistant", Slug: "tear-resistant", CreatedAt: time.Now()},
		{Name: "Ultra Thin", Slug: "ultra-thin", CreatedAt: time.Now()},
		{Name: "Heavy Duty", Slug: "heavy-duty", CreatedAt: time.Now()},
		{Name: "Eco Leather", Slug: "eco-leather", CreatedAt: time.Now()},
		{Name: "Minimal Packaging", Slug: "minimal-packaging", CreatedAt: time.Now()},
		{Name: "Quick Setup", Slug: "quick-setup", CreatedAt: time.Now()},
		{Name: "Bright White", Slug: "bright-white", CreatedAt: time.Now()},
		{Name: "Charcoal Grey", Slug: "charcoal-grey", CreatedAt: time.Now()},
		{Name: "Rainproof", Slug: "rainproof", CreatedAt: time.Now()},
		{Name: "Scratch Resistant", Slug: "scratch-resistant", CreatedAt: time.Now()},
		{Name: "Noise Canceling", Slug: "noise-canceling", CreatedAt: time.Now()},
		{Name: "Space Grey", Slug: "space-grey", CreatedAt: time.Now()},
		{Name: "Rose Gold", Slug: "rose-gold", CreatedAt: time.Now()},
		{Name: "Satin Finish", Slug: "satin-finish", CreatedAt: time.Now()},
		{Name: "Velvet Touch", Slug: "velvet-touch", CreatedAt: time.Now()},
		{Name: "Color Changing", Slug: "color-changing", CreatedAt: time.Now()},
		{Name: "Heat Resistant", Slug: "heat-resistant", CreatedAt: time.Now()},
		{Name: "Fingerprint Proof", Slug: "fingerprint-proof", CreatedAt: time.Now()},
		{Name: "Wireless Charging", Slug: "wireless-charging", CreatedAt: time.Now()},
		{Name: "USB-C", Slug: "usb-c", CreatedAt: time.Now()},
		{Name: "Bluetooth Enabled", Slug: "bluetooth-enabled", CreatedAt: time.Now()},
		{Name: "Built-In Speaker", Slug: "built-in-speaker", CreatedAt: time.Now()},
		{Name: "Magnetic", Slug: "magnetic", CreatedAt: time.Now()},
		{Name: "Stackable", Slug: "stackable", CreatedAt: time.Now()},
		{Name: "Precision Fit", Slug: "precision-fit", CreatedAt: time.Now()},
	}

	for _, category := range categories {
		if err := db.FirstOrCreate(&category, models.Category{Slug: category.Slug}).Error; err != nil {
			log.Printf("Gagal seeding category %s: %v\n", category.Name, err)
		}
	}

	log.Println("[SEEDER] ⚙️  categories seeded")
}
